networks:
  chicomm:
    driver: bridge
services:
  mysql:
    networks:
      - chicomm
    platform: linux/amd64
    image: mysql:8.4
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chicomm
  chicomm-grpc:
    networks:
      - chicomm
    hostname: chicomm-grpc
    platform: linux/amd64
    image: hns.test/chicomm:latest
    command: "/bin/chicomm-grpc"
    ports:
      - "9091:9091"
    environment:
      DB_ADDR: "mysql:3305"
    depends_on:
      - mysql
  chicomm-api:
    networks:
      - chicomm
    hostname: chicomm-api
    platform: linux/amd64
    image: hns.test/chicomm:latest
    command: "/bin/chicomm-api"
    ports:
      - "8080:8080"
    environment:
      GRPC_SVC_ADDR: "chicomm-grpc:9091"
    depends_on:
      - chicomm-grpc
  chicomm-notification:
    networks:
      - chicomm
    hostname: chicomm-notification
    platform: linux/amd64
    image: hns.test/chicomm:latest
    command: "/bin/chicomm-notification"
    environment:
      ADMIN_EMAIL: "admin@admin.com"
      ADMIN_PASS: "password"
      GRPC_SVC_ADDR: "chicomm-grpc:9091"
    depends_on:
      - chicomm-grpc